### ISSUE TITLE
Source of hid-gadget-test 

### ISSUE THREAD

**Issue by miaoski** [anbud/DroidDucky#1]
Hi.
Thanks for your brilliant blog.  It's very inspiring.
Is it possible to upload the source code of hid-gadget-test?
I really want to know how it works.
Thank you!

**Comment by anbud** [comment]
Thank you! 
You can find the source [here](https://github.com/pelya/android-keyboard-gadget/blob/master/hid-gadget-test/jni/hid-gadget-test.c).

**Comment by miaoski** [comment]
Thank you! :)
