### ISSUE TITLE
Unknown option: r

### ISSUE THREAD

**Issue by mato200** [anbud/DroidDucky#11]
After 1 and a half hour of finding working kernel for Redmi Note 4 and managing to setup everything right, HID is working but your example script u provided is not working 
[https://imgur.com/a/o3MMJRv](url)

it does execute to an extent but cmd at my home PC doesnt open, but the program starts to write weird shit in the start search (win 10)

btw: Svaka čast na projektu :)

**Comment by mato200** [comment]
Also, idk if this matters but i its my first time ever to see a .dd extension.
I just copy pasted ur example code into notepad++ and saved it as a file with .dd at the end

**Comment by mato200** [comment]
I may be onto something, do I need to encode the txt file somehow and what do you mean by unix line endings ?

**Comment by anbud** [comment]
Hey, sorry for the late response, I totally forgot about this project. 

Since it’s closed, did you manage to fix it? :)
