### ISSUE TITLE
Bash Error

### ISSUE THREAD

**Issue by Zabeh01** [anbud/DroidDucky#3]
Hello, I really appriciate for sharing this :) 

But i am getting error while executing the .sh and .dd file :(
I have download the droidducky and create one .dd file and transfered to the android phone.
I am using Terminal Emulator but when i write bash but throws errors and when i try to run that .sh file with sh it also throws me error I don't know please help . 
android version 4.2.2 :) 

thanks

**Comment by anbud** [comment]
Hello.
Have you installed a custom kernel for your device?
Also, please copy the errors you are getting here, so I can get to the bottom of it.

Thank you.

**Comment by Zabeh01** [comment]
Sir how ? No i don't :(

Sir i have samsung galaxy trend plus s7580 ? 
How can i do that ?

Please can you guide me step by step ? 
thanks 

Best regards

**Comment by anbud** [comment]
Hi. 
Sorry for the late reply. I'm sorry, but your device is not currently supported yet.
Kernel for your device will appear on [this page](https://github.com/pelya/android-keyboard-gadget) when it's available.

**Comment by Zabeh01** [comment]
Yeh, Sir But i want to compile it myself sir can you please guide me ? 
while patching the required file i get a lot of error I don't know how to solve it :(

please help if you can :) 

thanks

**Comment by anbud** [comment]
Hi.
Sorry, but I'm not a kernel developer and I don't have experience with that.
You should submit an issue for [this project](https://github.com/pelya/android-keyboard-gadget) (the original project _droidducky_ is based on).

**Comment by Zabeh01** [comment]
I sumbmitted but no answer :(

**Comment by anbud** [comment]
Since this issue is not directly connected to DroidDucky, I'm closing it.
Thank you.
