### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by Zabeh01** [anbud/DroidDucky#4]
Hello, 
Sir you might have seen this https://srlabs.de/badusb/ there is a little script with which we can spoof ethernet with android devices without flashing any custom kernel.
Sir cant we make a script that should act as a HID (Mouse/Keyboard) and use the RubberDucky Script ? 
I have seen the content of that script that is simple enough to understand and do you know can we use that in different way ? 

Best Regards

**Comment by anbud** [comment]
Hello.
I'll check it out. For now, I'm closing this, if there are any updates, you'll hear about it on my blog.
