### ISSUE TITLE
Payload is not working

### ISSUE THREAD

**Issue by Zabeh01** [anbud/DroidDucky#5]
Hello sir , Sir I have used this payload but it seems it is not working please check :) 

https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Payload---lock-your-computer-message

thanks

**Comment by anbud** [comment]
Hello.
I've just tried it out and got the following [result](http://snag.gy/1j6ik.jpg). It seems to work correctly.
Please check if your payload file has Unix line endings, as this is probably the reason why it doesn't work.
