### ISSUE TITLE
error: droidducky.sh: line 137: syntax error: bad substitution

### ISSUE THREAD

**Issue by Rosalie241** [anbud/DroidDucky#6]
I keep getting the error: droidducky.sh: line 137: syntax error: bad substitution
I chmodded the files
I am su
I tried everything so yea.

**Comment by Rosalie241** [comment]
Fixed it by installing bash for android.

**Comment by joaovictor07** [comment]
@tim241 Can you please send me a link of the bash that you used to fix that issue
Thanks

**Comment by Rosalie241** [comment]
@joaovictor07 https://play.google.com/store/apps/details?id=com.bitcubate.android.bash.installer
