### ISSUE TITLE
droidducky.sh: line 137: syntax error: bad substitution

### ISSUE THREAD

**Issue by evanuz** [anbud/DroidDucky#8]
Hello!!

When i try to execute the command:

bash droidducky.sh  foo       it gives me the error:

droidducky.sh: line 137: syntax error: bad substitution

i Have a Nexus 6 with PwnKernel ( http://forum.xda-developers.com/nexus-6/development/kernel-pwnkernel-pwn-networks-based-t3020048 )

If i run this command:

echo a | /data/local/tmp/hid-gadget-test /dev/hidg0 keyboard

It types correctly an "a".

Can you help me??

Thanks

**Comment by anbud** [comment]
Hello.

Does the file `foo` you are using have Unix line endings? That's the first thing that comes to mind.
